# Generated by Django 5.0.7 on 2024-11-19 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtp',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
