# Generated by Django 5.0.7 on 2024-11-24 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='name',
        ),
        migrations.AlterField(
            model_name='addtp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
