# Generated by Django 5.0.7 on 2024-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0002_remove_workshop_name_alter_addtp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
