# Generated by Django 5.1.3 on 2024-11-30 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0004_addtp_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
