# Generated by Django 5.1.3 on 2024-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0005_addtp_created_at_addtp_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtp',
            name='item',
            field=models.CharField(default=1, max_length=200, verbose_name='Изделие'),
            preserve_default=False,
        ),
    ]
