# Generated by Django 5.1.3 on 2024-12-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impotrttp', '0006_addtp_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название изделия')),
                ('description', models.TextField(verbose_name='Описание изделия')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='addtp',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impotrttp.item', verbose_name='Изделие'),
        ),
    ]
